simulation:
  num_vehicles: 2
  tick_rate: 0.1  # seconds
# 0.05s = 20 FPS (good for normal simulation)
# 0.033s = 30 FPS (smoother)
# 0.016s = 60 FPS (very smooth but more CPU intensive)
# 0.1s = 10 FPS (slower motion)

sensors:
  collision:
    enabled: true
  lane_invasion:
    enabled: true
  gnss:
    enabled: true
    noise_alt: 0.5
    noise_lat: 0.5
    noise_lon: 0.5
  imu:
    enabled: true
  lidar:
    enabled: true
    points_per_second: 600000
    rotation_frequency: 30
    channels: 64
    range: 100.0
    upper_fov: 15.0
    lower_fov: -35.0
    horizontal_fov: 360.0
    atmosphere_attenuation_rate: 0.004
    dropoff_general_rate: 0.45
    dropoff_intensity_limit: 0.8
    dropoff_zero_intensity: 0.4
    noise_stddev: 0.01
  radar:
    enabled: true
    horizontal_fov: 30
    points_per_second: 1500
  semantic_lidar:
    enabled: true
    points_per_second: 100000
    channels: 32
    range: 100.0

logging:
  enabled: false  # Enable/disable all logging
  level: INFO
  json:
    max_file_size_mb: 100
    indent: 2
  sensors:
    pointcloud:
      enabled: true
      formats: ['pcd']
      max_files_per_vehicle: 1000
    json:
      enabled: true
      include_other_vehicles: true
      max_file_size_mb: 100
  output:
    directory: "logs"
    timestamp_format: "%Y%m%d_%H%M%S"
